# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir P:/ENEL373/Lab_A01_group_15/Assignment.cache/wt [current_project]
set_property parent.project_path P:/ENEL373/Lab_A01_group_15/Assignment.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib P:/ENEL373/Lab_A01_group_15/Assignment.srcs/sources_1/new/alu_design.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc P:/ENEL373/Lab_A01_group_15/Assignment.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files P:/ENEL373/Lab_A01_group_15/Assignment.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc]


synth_design -top alu_design -part xc7a100tcsg324-3


write_checkpoint -force -noxdef alu_design.dcp

catch { report_utilization -file alu_design_utilization_synth.rpt -pb alu_design_utilization_synth.pb }
