# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir P:/ENEL373/labs/Week3Lab3Project2/Week3Lab3Project2.cache/wt [current_project]
set_property parent.project_path P:/ENEL373/labs/Week3Lab3Project2/Week3Lab3Project2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib P:/Downloads/two_digit_counter_for_PL2_lab_top_level_part_soln.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc P:/ENEL373/labs/Week3Lab3Project2/Week3Lab3Project2.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files P:/ENEL373/labs/Week3Lab3Project2/Week3Lab3Project2.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc]


synth_design -top counter_top_level -part xc7a100tcsg324-3


write_checkpoint -force -noxdef counter_top_level.dcp

catch { report_utilization -file counter_top_level_utilization_synth.rpt -pb counter_top_level_utilization_synth.pb }
